### ISSUE TITLE
Sensor-ID als uint8 1-255 editierbar

### ISSUE THREAD

**Issue by ronnyhartenstein** [CodeforChemnitz/sensor-map#6]
Statt Auto-ID soll die ID vom Nutzer eingegeben werden. 
Z.B. um Pin 6 direkt als ID 6 zu senden. Der Sensor auf Pin 6 kann leider leider nicht umgehangen werden.

**Comment by MorrisJobke** [comment]
So sollen Daten aussehen

``` json
{
    "uuid": "20b79b2689f8b971625b41b0fc1a1880804c64df0cea3ca71016766f9773a660",
    "data": {
        "3": 12.3,
        "5": 23423
    }
}
```
